fullnameOverride: wiki

fastapi:
  image_name: wiki-fastapi
  image_tag: latest
  replicaCount: 1
  servicePort: 8000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

postgres:
  image: postgres:15
  user: wiki
  password: wiki
  db: wiki
  storage: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

prometheus:
  image: prom/prometheus:v2.49.1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

grafana:
  image: grafana/grafana:10.4.2
  adminUser: admin
  adminPassword: admin
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

ingress:
  enabled: true
  className: ""
  host: ""
