apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wiki-chart.fullname" . }}-grafana
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "wiki-chart.fullname" . }}-grafana
  template:
    metadata:
      labels:
        app: {{ include "wiki-chart.fullname" . }}-grafana
        {{- include "wiki-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s/grafana"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: provisioning
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml
              readOnly: true
            - name: provisioning
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
              readOnly: true
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards/creation-dashboard.json
              subPath: creation-dashboard.json
              readOnly: true
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
      volumes:
        - name: provisioning
          configMap:
            name: {{ include "wiki-chart.fullname" . }}-grafana-provisioning
        - name: dashboards
          configMap:
            name: {{ include "wiki-chart.fullname" . }}-grafana-dashboard
