apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wiki-chart.fullname" . }}-postgres
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "wiki-chart.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "wiki-chart.fullname" . }}-postgres
        {{- include "wiki-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "wiki-chart.fullname" . }}-postgres
